### ISSUE TITLE
Freezing after failing to dump dsp firm.

### ISSUE THREAD

**Issue by robot-dev-ctr** [CyberYoshi64/SB-Download-Station#1]
Using Either Hax 2.9 (no cfw) or Luma3DS, It Crashes with rainbow dots on the top screen.

**Comment by CyberYoshi64** [comment]
Yup, looks like the DSP dump code inside the app has troubles doing its job.

Unfortunately, I have no clue, what went wrong but perhaps I should require the user to have dumped the DSP firm before, using the DSP1 app you get when following 3ds.guide, if they want sound coming out of the app.

The app will be completely silent, if the dspfirm.cdc isn't found or is bad and SFX (and maybe a BGM) will play, when the file is good.

**Comment by robot-dev-ctr** [comment]
> Yup, looks like the DSP dump code inside the app has troubles doing its job.
> 
> Unfortunately, I have no clue, what went wrong but perhaps I should require the user to have dumped the DSP firm before, using the DSP1 app you get when following 3ds.guide, if they want sound coming out of the app.
> 
> The app will be completely silent, if the dspfirm.cdc isn't found or is bad and SFX (and maybe a BGM) will play, when the file is good.
> 
> EDIT: Basically, the app would work no matter what.
> 
> Thanks for the report! I'll be removing the code handling it and improve the SFX functions, since they will crash everything if triggered.

I fixed it by compilinga 3dsx version of DSP1(because I use hax2.9 not cfw.) and then copying it into the SBDownloadStation/dumps folder.
you can find it her https://github.com/robot-dev-ctr/DSP1-userland.git

**Comment by CyberYoshi64** [comment]
> I fixed it by compilinga 3dsx version of DSP1(because I use hax2.9 not cfw.) and then copying it into the SBDownloadStation/dumps folder.
> you can find it her https://github.com/robot-dev-ctr/DSP1-userland.git

The DSP firm should be placed in /3ds as dspfirm.cdc.

BTW the /SBDownloadStation folder will become useless since I changed the folder names, so they don't cause 2 similar folders to exist.

Also, (using new folder name) /SB-Download-Station/data/dumps is the place to backup SmileBASIC projects, so they can be used for submission on the SB3-DS-Projects repository. It was not intended to be used to store the DSP firm.

**Comment by robot-dev-ctr** [comment]
Whoops, Oh yeah something screwed up and deleted my dsp dump.
